// ─── Corn Hub CLI — Environment Configuration ───────────────────
// Handles Voyage AI API key, .env file management, MCP API key generation

import { join } from 'node:path';
import { pathExists, readTextFile, writeTextFile, randomHexSync } from './utils.js';
import * as ui from './ui.js';

export interface EnvConfig {
  voyageApiKey: string;
  mcpApiKey: string;
  embeddingModel: string;
  embeddingDims: string;
}

export async function configureEnvironment(installDir: string): Promise<EnvConfig> {
  ui.blank();

  // ── Voyage AI API Key ──────────────────────────────────────────
  ui.info('Corn Hub uses Voyage AI for code embeddings (semantic search).');
  ui.info('Get a free API key at: https://dashboard.voyageai.com/api-keys');
  ui.blank();

  let voyageApiKey = '';

  // Check if we already have one in .env
  const existingEnv = readExistingEnv(installDir);
  if (existingEnv.OPENAI_API_KEY && existingEnv.OPENAI_API_KEY !== 'pa-...') {
    ui.success(`Found existing Voyage AI key: ${maskKey(existingEnv.OPENAI_API_KEY)}`);
    const keepExisting = await ui.confirm('Keep this API key?', true);
    if (keepExisting) {
      voyageApiKey = existingEnv.OPENAI_API_KEY;
    }
  }

  if (!voyageApiKey) {
    voyageApiKey = await ui.promptSecret('Enter your Voyage AI API key');

    if (!voyageApiKey) {
      ui.warn('No API key provided. Corn Hub will use fallback hash-based embeddings.');
      ui.info('You can add the key later in infra/.env (OPENAI_API_KEY=pa-...)');
      voyageApiKey = '';
    } else if (!voyageApiKey.startsWith('pa-')) {
      ui.warn('Key does not start with "pa-". Voyage AI keys typically start with "pa-".');
      const proceed = await ui.confirm('Continue with this key anyway?', true);
      if (!proceed) {
        voyageApiKey = '';
      }
    }
  }

  // ── Generate MCP API Key ───────────────────────────────────────
  const mcpApiKey = randomHexSync(32);
  ui.success(`Generated MCP API key: ${maskKey(mcpApiKey)}`);

  const config: EnvConfig = {
    voyageApiKey,
    mcpApiKey,
    embeddingModel: 'voyage-code-3',
    embeddingDims: '1024',
  };

  // ── Write .env files ───────────────────────────────────────────
  writeEnvFiles(installDir, config);

  return config;
}

function readExistingEnv(installDir: string): Record<string, string> {
  const paths = [
    join(installDir, 'infra', '.env'),
    join(installDir, '.env'),
  ];

  for (const envPath of paths) {
    if (pathExists(envPath)) {
      const content = readTextFile(envPath);
      const env: Record<string, string> = {};
      for (const line of content.split('\n')) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const eqIdx = trimmed.indexOf('=');
        if (eqIdx === -1) continue;
        env[trimmed.slice(0, eqIdx).trim()] = trimmed.slice(eqIdx + 1).trim();
      }
      return env;
    }
  }
  return {};
}

function writeEnvFiles(installDir: string, config: EnvConfig): void {
  const buildDate = new Date().toISOString().split('T')[0];

  // ── infra/.env (for Docker) ────────────────────────────────────
  const infraEnv = `# Corn Hub — Docker Environment
# Generated by corn-install on ${buildDate}

# ── Voyage AI (for mem9 embeddings) ───
OPENAI_API_BASE=https://api.voyageai.com/v1
OPENAI_API_KEY=${config.voyageApiKey || 'pa-...'}

# ── Embedding Model ──────────────────────────
MEM9_EMBEDDING_MODEL=${config.embeddingModel}
MEM9_EMBEDDING_DIMS=${config.embeddingDims}

# ── MCP API Keys ─────────────────────────────
MCP_API_KEYS=${config.mcpApiKey}

# ── Build metadata ───────────────────────────
COMMIT_SHA=dev
BUILD_DATE=${buildDate}
`;

  writeTextFile(join(installDir, 'infra', '.env'), infraEnv);
  ui.success('Saved infra/.env (Docker environment)');

  // ── Root .env (for local dev) ──────────────────────────────────
  const rootEnv = `# Corn Hub — Environment Configuration
# Generated by corn-install on ${buildDate}

# ── Voyage AI (for mem9 embeddings) ───
OPENAI_API_BASE=https://api.voyageai.com/v1
OPENAI_API_KEY=${config.voyageApiKey || 'pa-...'}

# ── Embedding Model ──────────────────────────
MEM9_EMBEDDING_MODEL=${config.embeddingModel}
MEM9_EMBEDDING_DIMS=${config.embeddingDims}

# ── MCP API Keys ─────────────────────────────
MCP_API_KEYS=${config.mcpApiKey}

# ── Build metadata ───────────────────────────
COMMIT_SHA=dev
BUILD_DATE=${buildDate}
`;

  writeTextFile(join(installDir, '.env'), rootEnv);
  ui.success('Saved .env (local development)');
}

function maskKey(key: string): string {
  if (key.length <= 6) return '***';
  return key.slice(0, 3) + '•'.repeat(Math.min(key.length - 6, 20)) + key.slice(-3);
}
